services:
  db:
    image: postgres:18
    container_name: interval_insights_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: interval_insights_dev
      POSTGRES_USER: interval_user
      POSTGRES_PASSWORD: interval_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data: